name: Build Rafiq Al-Quran Android

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build APK and AAB
    runs-on: ubuntu-latest

    steps:

      # 1. تحميل ملفات المشروع من GitHub
      - name: Checkout repository
        uses: actions/checkout@v4


      # 2. تثبيت Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      # 3. تثبيت Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable


      # 4. عرض الملفات للتأكد
      - name: Show repository files
        run: |
          echo "Repository files:"
          find . -maxdepth 2 -type f | head -100
